# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

target 'FindMyFurryFriend' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for FindMyFurryFriend
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Toast-Swift',  '~> 3.0.1'

end
